Add GitHub Actions Continuous Integration service
cooljeanius/gcta pull request #2
Opened 2021-05-10 07:15 UTC by richelbilderbeek

Dear GCTA maintainer,

I have added a GitHub Actions build script. Now, under the 'Actions' tab of your repo, one can see if the GCTA installation still works. `./configure` goes awesome. `make` however, for now, fails, I guess something changed in the dependencies.

If the compile error in `make` is fixed, it would be great to add a build badge, so others can see the quality of your work! I volunteer to add these as well.

Cheers, Richel

2021-05-12 10:15 UTC, cooljeanius commented
oh yeah I haven't been able to get `make` to succeed yet on my own machine, either; I'd want to get things fixed locally first before trying to verify things with GitHub Actions

2021-05-12 10:53 UTC, cooljeanius requested changes
this file is unnecessary

2021-05-12 13:02 UTC, richelbilderbeek commented
@cooljeanius processed your feedback :+1:

2021-05-13 01:17 UTC, cooljeanius approved these changes

2021-05-13 01:17 UTC, merged